{{- if .Values.db.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "example-chart.fullname" . }}-db-seed
  labels:
    {{- include "example-chart.labels" . | nindent 4 }}
    app: job-db-seed
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        {{- include "example-chart.selectorLabels" . | nindent 8 }}
        app: job-db-seed
    spec:
      serviceAccountName: {{ include "example-chart.serviceAccountName" . }}
      restartPolicy: Never
      containers:
      - name: redis-seed
        image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
        command: ["/bin/sh", "-c"]
        args:
        - >
          redis-cli -h {{ include "example-chart.fullname" . }}-db-svc
          -a "$REDIS_PASSWORD"
          SET gantry:example '{"message":"Hello from Gantry Example Chart","timestamp":"2026-05-06"}'
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "example-chart.fullname" . }}-secret
              key: redis-password
{{- end }}
